### ISSUE TITLE
ATube is dead

### ISSUE THREAD

**Issue by ios7jbpro** [HotarunIchijou/fluent-design-app-list#1]
the app doesnt exist on ms store anymore for some reason

**Comment by HotarunIchijou** [comment]
Yeah, it seems to be deleted from msstore, but I don't know if I should remove it from the list

**Comment by ios7jbpro** [comment]
The build doesnt work either. It doesnt load videos anymore

**Comment by HotarunIchijou** [comment]
Okay, removed
