### ISSUE TITLE
Add Universal x86 Tuning Utility, Ryujinx and Bloxstrap

### ISSUE THREAD

**Issue by asdf2147483647** [HotarunIchijou/fluent-design-app-list#2]
**Universal x86 Tuning Utility is a tool designed to assist users in optimising the performance and settings of their x86 laptops and computers.**
[Source code](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/)

![image](https://github.com/user-attachments/assets/b3c731d4-80c1-415a-beb9-be2c6769c34e)

**Ryujinx is an open-source Nintendo Switch emulator written in C#.**
[Source code](https://github.com/Ryujinx/Ryujinx)

![image](https://github.com/user-attachments/assets/642d34cc-8364-438f-9f2e-a31ad1e01813)

**Bloxstrap is a third-party replacement for the standard Roblox bootstrapper, providing additional useful features and improvements.**
[Source code](https://github.com/pizzaboxer/bloxstrap)

![image](https://github.com/user-attachments/assets/a2dcef9a-2a16-43de-9771-b6a56870fd41)

**Comment by HotarunIchijou** [comment]
Added, thanks
